### ISSUE TITLE
Draft for extensible, mutually-exclusive packages

### ISSUE THREAD

**Issue by memo33** [memo33/sc4pac-tools#10]
In some use cases, it can be useful to declare packages as **mutually exclusive** (for example, different night mods or different terrain mods). The number of those packages shouldn't fixed, but should be **extensible** (there can be many terrain mods). This is in contrast to the current use of variants, which usually select from a fixed list of values.

Some ideas:

### Approach 1

Taking night mods as example:

We could define an abstract package `meta:nightmode-mod` that represents a capability "night mod". DN buildings can depend on this abstract package instead of a concrete implementation of a night mod (like `simfox:day-and-nite-mod`):
```yaml
dependencies: [ meta:nightmode-mod ]
```

Actual night mod packages like `simfox:day-and-nite-mod` must declare that they implement this capability, for example:
```yaml
group: simfox
name: day-and-nite-mod
variants:
- variant: { nightmode: standard }
- variant: { nightmode: dark }
  implements: [ meta:nightmode-mod ]
```

Then, when the abstract package `meta:nightmode-mod` gets installed as dependency of a DN building, sc4pac would look for all known implementations and offer to select exactly one of them. Gizmo's night mod would be another implementation. It could even be defined in a different channel.

This approach is not entirely orthogonal to variants, which also encode mutual exclusivity, so there's some overlap.

### Approach 2

Instead of encoding the night mod capability as a "package", it could be encoded as a "variant", which seems closer to the currently existing functionality.

A DN building would define these variants:
```yaml
variant: { nightmode: standard }
variant: { nightmode: dark, nightmode-mod: * }
```
Instead of adding the field `dependencies: [ simfox:day-and-nite-mod ]`, we use `nightmode-mod: *` to say that **any** nightmode mod is needed. It also implies that the list of possible `nightmode-mod` values is extensible, so sc4pac needs to search globally for possible values to select.

A nightmode mod package would look like:
```yaml
group: simfox
name: day-and-nite-mod
variants:
- variant: { nightmode: standard }
- variant: { nightmode: dark, nightmode-mod: simfox }
  implements: [ nightmode-mod: * ]  # something like this is needed so that sc4pac can tell this is an 'extensible' variant
```

When you install a DN building, sc4pac would search for all known values that can fill in for `nightmode-mod: *` and let you select one of them. Again, other night mods could be defined in different channels.

---

Both approaches should work more or less the same for other basic "capabilities" (terrain mods, tree controllers, rock, beach, water mods). Though, there's not usually any package that would declare these as dependencies.

It would be great to have examples of more complex uses cases in order to check whether one or the other approach would break.

**Comment by Zasco** [comment]
> ### Approach 2

I prefer this solution. It's light, simple, widely understood and doesn't add much to the existing _sc4pac_ framework. I would get rid of the added "_implements_" however. Unless I didn't grab the implications of the approach, it is not needed. This would offer a lot of flexibility as this configuration would be possible:
``` YAML
variant: { nightmode: standard }
variant: { nightmode: dark, nightmode-mod: * }
variant: { nightmode: dark, nightmode-mod: simfox:day-n-nite }
```

**Comment by memo33** [comment]
> I would get rid of the added "_implements_" however. Unless I didn't grab the implications of the approach, it is not needed.

There needs to be a way for sc4pac to identify packages that can be referenced in that way so that it knows what to show as selection dialog when installing a package with `nightmode-mod: *`. Either explicitly via a field like "implements". Or perhaps implicitly by requiring that the value of `nightmode-mod` is _equal_ to the package identifier of night mods:
```yaml
group: simfox
name: day-and-nite-mod
variants:
- variant: { nightmode: standard }
- variant: { nightmode: dark, nightmode-mod: simfox:day-and-nite-mod }
```
It would more clearly represent a dependency relationship that way if referenced from another package like you suggested.

**Comment by noah-severyn** [comment]
Throwing another opinion into the mix, **Approach 1** is much more intuitive to me, considering a mod is dependent on ***a*** night mode mod, not any one in particular. However, I would be much more in favor of a simpler syntax like
```yaml
group: simfox
name: day-and-nite-mod
implements: [ meta:nightmode-mod ]
```
which IMO more clearly defines the ***is a*** relationship. A package or variant requires a night mode mod. `simfox:day-and-nite-mod` is a night mode mod. The other syntaxes with multiple variant key:value pairs are rather confusing to me.

The `implements` property could be protected and only allow a few, pre-approved values for water/rock/terrain/etc. mods.

**Comment by memo33** [comment]
Thanks for your input. 

> The other syntaxes with multiple variant key:value pairs are rather confusing to me. Please let me know if I'm missing something here.

The syntax with the multiple variants like
```yaml
group: simfox
name: day-and-nite-mod
variants:
- variant: { nightmode: standard }
- variant: { nightmode: dark }
  implements: [ meta:nightmode-mod ]
```
is a safeguard to ensure that the DN mod isn't accidentally installed when `nightmode: standard` was selected. The mod is already [defined like that](https://github.com/memo33/sc4pac/blob/b33ed334872a78e73677238cc421c72874a6ccad/src/yaml/simfox/day-and-nite-mod.yaml#L6-L10).


In order to decide what to do here, do any of you have more complex use cases that maybe work better with one of the approaches than the other?
