### ISSUE TITLE
Consider global season variant

### ISSUE THREAD

**Issue by sebamarynissen** [memo33/sc4pac-tools#16]
I'm currently working on a mod that makes all trees made by Girafe semi-seasonal. With this I mean that depending what file you have in your plugins (z_fall, z_winter, z_summer, z_snow), the trees have your preferred appearance, regardless of whether they were actually planted as seasonal, evergreen or everwinter, inspired by the approach used in the [Central European Tree
 Controller](https://community.simtropolis.com/files/file/31419-central-european-tree-controller/).

I implemented the proof of concept today and hope to release it somewhere this week after some polishing. Obviously I also plan to write metadata for it so that it can be installed with sc4pac, which is especially useful because sc4pac makes it dead easy to switch between seasons by the use of variants.

While I was thinking about this, I was wondering whether it makes sense to introduce a global season preference. That would allow me to change both the CETC season and the season of my Girafe patch at the same time. I also plan on making a similar mod for other seasonal props and flora (for example cycledoggs's trees), so it would be nice to be able to switch seasons all at once instead of per variant.

I was thinking of the following possible values
 - `fall`, but could be called autumn as well
 - `winter`
 - `snow` This could default to the winter variant if a package does not define a specific snow variant
 - `spring` This could default to the summer variant if the package does not define it
 - `summer` This could be the global default if a package does not define fall or winter. Could also be named evergreen/static, or both could exist (where evergreen is global default then)
 - `seasonal` If this is not defined, then default to evergreen

Something to be aware of though is that a value of seasonal might actually be incompatible with any of the other values. For example, the CETC does allow you to switch between summer, winter and fall, but *not* between those and seasonal. That's actually already the case now with the CETC, but if this would be a global variant, it becomes something users need to be aware of.

I know that this is kind of a niche problem, but I think it is worth considering. What's your opinion, @memo33 ?

An example of what the metadata could look like for such a package:
```yaml
 - variant: { season: summer }
   assets:
     - assetId: girafe-patch
       include: [ "_SUMMER\.dat" ]
 - variant: { season: fall }
   assets:
     - assetId: girafe-patch
       include: [ "_FALL\.dat" ]
 - variant: { season: winter }
   assets:
     - assetId: girafe-patch
       include: [ "_WINTER\.dat" ]
 - variant: { season: snow }
   assets:
     - assetId: girafe-patch
       include: [ "_SNOW\.dat" ]
 - variant: { season: seasonal }
   assets: []
```

**Comment by memo33** [comment]
The main problems I see with this that
- switching between already installed variants is not allowed by some packages
- some packages support only a subset of the variants.

Such "incomplete" variants are not really intended currently. It leads to conflicts when installing a variant that is not supported by a package. There aren't any fallback mechanisms.

As switching variants would be done rather infrequently presumably, I'm not sure it's worth it to implement something special along those lines. Choosing variants case-by-case for each package is probably fine. If packages were _designed to work together_, they can use the same variant even, so you could re-use the variants of the CETC for example.

@Zasco might have some ideas on this topic.

**Comment by sebamarynissen** [comment]
Yeah, I understand it's kind of a niche thing. It's probably not worth the effort like you say. I really like the "static seasonal" strategy though of the CETC and I could imagine creators providing various versions of their lots for example. If there is a variant per lot, it can get quickly out of hand.

Still, it's unlikely that a creator would release 4 different versions of every lot they make: a seasonal, summer, fall and winter version. If they intend their lot to be used like that, they'll be better off creating it as seasonal and then refer to my mod that I'm about to create.

As I mentioned before, I plan on releasing a mod for Girafe's flora, but in the end the goal is to have it available for all seasonal flora. Would it be a good idea then to have a kind of "dummy" package that defines a variant, such as
```yaml
group: smf-16
name: flora
variants:
  - variant: { smf-16:flora:season: fall }
  - variant: { smf-16:flora:season: winter }
  - variant: { smf-16:flora:season: snow }
  - variant: { smf-16:flora:season: summer }
  - variant: { smf-16:flora:season: seasonal }
```
and then other packages I make can use those variants?

Alternatively I could also just put everything in one package. I'm doing the Girafe flora now, so I could release it once that is done, and then add other seasonal flora later on in the same package. That way a local variant is sufficient.
