### ISSUE TITLE
Add support for clickteam installers

### ISSUE THREAD

**Issue by sebamarynissen** [memo33/sc4pac-tools#2]
I wanted to start adding metadata for [Aaron Graham's](https://community.simtropolis.com/profile/226625-aaron-graham/content/?type=downloads_file) content, but unfortunately [most of his downloads](https://community.simtropolis.com/files/file/28981-nybt-gracie-manor/) are [Clickteam](https://www.clickteam.com/install-creator-2-unreg) installers, so `sc4pac` cannot work with them.

I found a tool called [cicdec](https://github.com/Bioruebe/cicdec) that is able to extract files from this kind of installers. Hence I suggest that support for it is added to `sc4pac` too. To support it in the metadata, I suggest that we add a field to the asset yaml file, something like
```yaml
assetId: some-installer
version: 1.0.0
lastModified: "2024-03-22T00:00:00.000Z"
url: https://community.simtropolis.com/?do=download
type: clickteam-installer
```

I'd love to try and implement this, but I have no experience with Scala, so I might need some guidance here. Is it possible to run and build the code on Windows?
